### ISSUE TITLE
PJax loading with Ko-Fi

### ISSUE THREAD

**Issue by ArchBlood** [GreenMeteor/humhub-ko_fi-module#3]
There is a slight bug in the loading of the Ko-Fi button where if you try loading HumHub from a tab change any page that the Ko-Fi button is rendered on will break the `div` tags and load over top the page.

Have reported to Ko-Fi about such an issue just in case it's on their end, will monitor the issue closely

**Comment by ArchBlood** [comment]
Sad but it seems that Ko-Fi doesn't support PJax loading, which is a problem as PJax fetches and inserts new content _**without**_ refreshing the page which is required by HumHub, of course, you can turn PJax loading off but then it'll load sluggishly for some, so all I can do at this time is hope that Ko-Fi staff will do something about this for the future of their platform as Patreon did when we reported a similar issue.

**Comment by Ace2213** [comment]
Isn't it possible to prohibit the module from inserting the content until after the page is done loading?

Sorry, I don't really know how PJax works. When you say that disabling it will make the website more sluggish for some users, do you mean those on older browsers? Because my SSL settings already prohibit access for anyone who doesn't have support for TLSv1.2+

**Comment by Ace2213** [comment]
Like you said, it happens whenever you try to load a page that the module appears on using the navbar.

From my testing, this never happens if you access the page using a link or by opening in a new tab, in which case the entire page needs to load.

If that's what you mean by PJax, the loading of pages without reloading the entire page, then I have to say there isn't much difference in the loading times for me. It is slightly faster, but not noticeably so.

Hopefully this is helpful information.

**Comment by ArchBlood** [comment]
To better understand what PJax brings to the table I suggest reading up from this [source](https://github.com/defunkt/jquery-pjax).

**Comment by ArchBlood** [comment]
Closing now as we've switched to using the Ko-fi image button method provided by Ko-fi.
